name: animalogy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  animated_splash_screen: ^1.3.0
  fluttermoji: ^1.0.2
  just_audio: ^0.9.34
  shared_preferences: ^2.0.18
  sizer: ^2.0.15
  flutter_screenutil: ^5.7.0
  simple_animations: ^4.2.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/Backgrounds/
    - assets/Drongo/
    - assets/Meerkat/